branches:
  only:
    - master
    - dev
language: python
python:
  - "3.5"
  - "3.6"
install:
  - sudo apt-get install graphviz
  - pip install -r requirements.txt
script:
  - python -m unittest test/test_processing.py
  - python -m unittest test/test_utilities.py
  - python -m unittest test/test_modeling.py
  - python setup.py sdist bdist_wheel
  - pip install dist/adhoc-0.1-py3-none-any.whl
  - cd notebooks
  - python usage-processing.py
  - python usage-modeling.py
