branches:
  only:
    - master
    - dev
language: python
python:
  - "3.7"
install:
  - sudo apt-get install graphviz
  - pip install -r requirements.txt
script:
  - pytest --cov-report term --cov=ad_hoc test/
  - codecov
  - python setup.py sdist bdist_wheel
  - pip install dist/ad_hoc-0.4-py3-none-any.whl
  - cd notebooks
  - python usage-processing.py
  - python usage-modeling.py
  - python sample-diagrams.py
